spring
  cloud:
    config:
      discovery:
        enabled: false
        service-id: config-server

config:
  test:
    value: default-config
---
spring:
  config:
    activate:
      on-profile: dev
   
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"

server:
  port: 8084
  
config:
  test:
    value: dev-config

---
spring:
  config:
    activate:
      on-profile: test
   
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8763/eureka"

server:
  port: 8086
  
config:
  test:
    value: test-config
